name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://user:password@localhost:5432/tanstarter
      VITE_BASE_URL: http://localhost:3000
      BETTER_AUTH_SECRET: test_secret
      NETLIFY_IDENTITY_SITE: http://localhost:9999
      NETLIFY_IDENTITY_AUD: ""
      GITHUB_CLIENT_ID: ""
      GITHUB_CLIENT_SECRET: ""
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.x"

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run check-types

      - name: Run tests
        run: bun run test -- --run
